## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

ModuleNotFoundError: No module named 'tensorflow'

In [23]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [24]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [25]:
# Look at APPLICATION_TYPE value counts for binning
value_count = application_df['APPLICATION_TYPE'].value_counts()
value_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [26]:
application_types_to_replace = list(value_count[value_count<500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [27]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(value_count[value_count<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [28]:
# Look at CLASSIFICATION value counts for binning
class_value_count = application_df['CLASSIFICATION'].value_counts()
class_value_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [29]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_value_count[class_value_count>1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [30]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_value_count[class_value_count<500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [31]:
# Convert categorical data to numeric with `pd.get_dummies`
df_dummies = pd.get_dummies(application_df)
df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [32]:
# Split our preprocessed data into our features and target arrays
y = df_dummies['IS_SUCCESSFUL']
X = df_dummies.drop(columns='IS_SUCCESSFUL')
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [33]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [20]:
X_train

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
10679,1,5000,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
5052,1,5000,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
9990,1,5000,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
25173,1,5000,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
11405,1,5000,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,1,5000,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
32511,1,5000,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
5192,1,5000,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
12172,1,5000,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
33003,1,5000,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = 44
hidden_nodes_layer1 =  10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 10)                450

 dense_10 (Dense)            (None, 5)                 55

 dense_11 (Dense)            (None, 1)                 6

=================================================================
Total params: 511 (2.00 KB)
Trainable params: 511 (2.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [40]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=30)

Epoch 1/30
804/804 [==============================] - 3s 2ms/step - loss: 0.6176 - accuracy: 0.6903
Epoch 2/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5742 - accuracy: 0.7259
Epoch 3/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5673 - accuracy: 0.7267
Epoch 4/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7282
Epoch 5/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5594 - accuracy: 0.7282
Epoch 6/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5546 - accuracy: 0.7285
Epoch 7/30
804/804 [==============================] - 3s 4ms/step - loss: 0.5519 - accuracy: 0.7284
Epoch 8/30
804/804 [==============================] - 3s 4ms/step - loss: 0.5510 - accuracy: 0.7289
Epoch 9/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7300
Epoch 10/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7301
Epoch 11/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7298
Epoch 12/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7315
Epoch 13/30
804/804 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7309
Epoch 14/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7304
Epoch 15/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7316
Epoch 16/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7321
Epoch 17/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7304
Epoch 18/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7328
Epoch 19/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7323
Epoch 20/30
804/804 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7316
Epoch 21/30
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7327
Epoch 22/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7326
Epoch 23/30
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7332
Epoch 24/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7331
Epoch 25/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7335
Epoch 26/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7332
Epoch 27/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7322
Epoch 28/30
804/804 [==============================] - 3s 3ms/step - loss: 0.5457 - accuracy: 0.7331
Epoch 29/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7336
Epoch 30/30
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7325

In [41]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5540 - accuracy: 0.7296 - 468ms/epoch - 2ms/step
Loss: 0.5539729595184326, Accuracy: 0.7295626997947693

In [45]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')